<?php

/**
 * @file
 * Contains transcode_profile.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function transcode_profile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the transcode_profile module.
    case 'help.page.transcode_profile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Video transcode profile manager') . '</p>';
      return $output;

    default:
  }
}
